defaults:
  field_health:
    description: Default field health monitor description
    aggregation_time_interval: day
    use_important_fields: true
    labels:
      - default
  volume:
    description: Default volume monitor description
    severity: SEV-1