source: snowflake
dbs:
  rentaldata:
    dim_listings_cleansed:
      schema: dev
      monitors:
        sev0:
          - freshness
          - volume
      timestampField: created_at
    fct_reviews_cleansed:
      schema: dev
      monitors:
        sev1:
          - field_health
      timestampField: review_date
  rentaldata2:
    dim_listings_cleansed2:
      schema: dev
      monitors:
        sev0:
          - freshness
      timestampField: created_at

# volume:
#   tables:
#     - table1
#     - table2
#   options:
#     table1:
#       option1: yes