source: snowflake
dbs:
  rentaldata:
    dim_listings_cleansed:
      schema: dev
      monitors:
        sev0:
          - freshness
          - volume
      timestamp_field: created_at
    fct_reviews_cleansed:
      schema: dev
      monitors:
        sev1:
          - field_health
      timestamp_field: review_date
  rentaldata2:
    dim_listings_cleansed2:
      schema: dev
      monitors:
        sev0:
          - freshness
      timestamp_field: created_at

dev: #schema
  rentaldata: #db
    field_health: #monitor_type
      dim_listings_cleansed: #table
        
